import type { Metadata } from 'next';
import { Urbanist } from 'next/font/google';
import './globals.css';
import Loader from './loader';

const urbanist = Urbanist({
  variable: '--font-urbanist',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Refly Agency',
  description: 'Refly Agency is a creative digital agency specializing in web development, branding, and marketing solutions to help businesses grow online.',
  keywords: [
    'Refly Agency',
    'Digital Agency',
    'Web Development',
    'Branding',
    'Marketing',
    'SEO',
    'Social Media',
    'Design',
    'UI/UX Design',
    'App Development',
    'Software Solutions',
    'Creative Studio',
    'Online Marketing',
    'Content Marketing',
    'Digital Strategy',
    'Graphic Design',
    'Logo Design',
    'Web Design',
    'Advertising',
    'Brand Strategy',
    'E-commerce Solutions',
    'Social Media Management',
    'Email Marketing',
    'Web App Development',
    'Mobile App Development',
    'Tech Solutions',
    'Startup Branding',
    'Digital Campaigns',
    'SEO Optimization',
    'Website Maintenance',
    'Performance Marketing',
    'Influencer Marketing',
    'Creative Agency',
    'Digital Transformation',
    'Marketing Automation',
    'PPC Management',
    'Social Media Ads',
    'Visual Design',
    'Brand Identity',
    'Online Presence',
    'Marketing Consulting',
    'Growth Hacking',
    'Content Strategy',
    'UX Research',
    'Front-End Development',
    'Back-End Development',
    'Full-Stack Development',
    'AI Solutions',
    'Analytics & Insights',
    'Marketing Analytics',
    'Cloud Solutions',
    'IT Consulting',
    'Enterprise Software',
    'Mobile Apps',
    'Software Development',
    'Systems Limited',
    '10Pearls',
    'NetSol Technologies',
    'CureMD',
    'Cubix',
    'Xavor Corporation',
    'Vaival Technologies',
    'Xeven Solutions',
    'Suave Solutions',
    'Clustox',
    'CodesOrbit Pvt. Ltd.',
    'CodeNinja',
    'Novatore Solutions',
    'Vizz Web Solutions',
    'Nasnix Pvt. Ltd.',
    'Arpatech',
    'Folio3',
    'Avanza Solutions',
    'TRG Tech',
    'Arbisoft',
    'Simform',
    'Bravado Solutions',
    'DeliveryDevs',
    'BariTechSol',
    'ARFASOFTECH',
    'MindGigs',
    'TPS Worldwide',
    'Toptal Pakistan',
    'Xtreem Solution',
    'InvoZone',
    'Creative Chaos',
    'TechAbout',
    'DPL Technologies',
    'VentureDive',
    'Elixir Technologies',
    'Codebrik',
    'Techlogix',
    'i2c Inc.',
    'Trillium Technologies',
    'Cuberto',
    'DotLogics',
    'Zameen Digital',
    'Confiz',
    '10X Solutions',
    'Techwurx',
    'Pakistan Software Export Board',
    'TechAce Solutions',
    'Kualitatem',
    'Evolv Digital',
    'Pixel Hive',
    'Orbit Solutions',
    'Digital Horizon',
    'Code & Spark',
    'Vertex Labs',
    'Elevate Agency',
    'Core Creative',
    'Brand Sphere',
    'Flux Media',
    'Wave Digital',
    'Edge Studio',
    'Ignite Lab',
    'Luminous Designs',
    'Visionary Labs',
    'Nova Digital',
    'Quantum Studio',
    'Axis Creative',
    'Pulse Media',
    'Horizon Studio',
    'Rise Labs',
    'Neural Hive',
    'AI Nexus',
    'Cognitive Labs',
    'MachineMind',
    'DeepVision AI',
    'IntelliCore',
    'AlgoWorks',
    'DataSphere',
    'Quantum AI',
    'SmartBot Labs',
    'Predictive Solutions',
    'Visionary AI',
    'Synapse Studio',
    'AI Orbit',
    'NeuroTech',
    'BotForge',
    'AI Innovations',
    'Cortex Solutions',
    'AI Engine',
    'FutureMind AI',
  ],
  authors: [{ name: 'Refly Agency', url: 'https://refly.agency' }],
  creator: 'Refly Agency',
  publisher: 'Refly Agency',
  robots: {
    index: true,
    follow: true,
    nocache: false,
    googleBot: {
      index: true,
      follow: true,
      noimageindex: false,
      'max-video-preview': -1,
      'max-image-preview': 'large',
      'max-snippet': -1,
    },
  },
  icons: {
    icon: [{ url: '/favicon.ico' }],
    shortcut: [{ url: '/favicon-32x32.png' }],
    apple: [{ url: '/apple-touch-icon.png' }],
  },
  manifest: '/manifest.json',
  themeColor: [
    { media: '(prefers-color-scheme: light)', color: '#ffffff' },
    { media: '(prefers-color-scheme: dark)', color: '#000000' },
  ],
  openGraph: {
    title: 'Refly Agency',
    description: 'Refly Agency is a creative digital agency specializing in web development, branding, and marketing solutions to help businesses grow online.',
    url: 'https://refly.agency',
    siteName: 'Refly Agency',
    images: [
      {
        url: '/og-image.png',
        width: 1200,
        height: 630,
        alt: 'Refly Agency - Creative Digital Agency',
      },
    ],
    locale: 'en_US',
    type: 'website',
  },
  twitter: {
    card: 'summary_large_image',
    title: 'Refly Agency',
    description: 'Refly Agency is a creative digital agency specializing in web development, branding, and marketing solutions to help businesses grow online.',
    site: '@ReflyAgency',
    creator: '@ReflyAgency',
    images: ['og-image.png'],
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const jsonLd = {
    '@context': 'https://schema.org',
    '@type': 'Organization',
    name: 'Refly Agency',
    url: 'https://refly.agency',
    logo: 'https://refly.agency/logo.png',
    sameAs: [
      'https://www.forbes.com/top-companies/',
      'https://www.inc.com/inc5000',
      'https://www.crunchbase.com/hub/top-software-companies',
      'https://www.clutch.co/directory',
      'https://www.goodfirms.co/directory',
      'https://www.topdevelopers.co/directory',
      'https://www.appfutura.com/directory',
      'https://www.designrush.com/agency',
      'https://www.99firms.com/directory',
      'https://www.sortlist.com/directory',
      'https://www.expertmarket.co.uk/software-companies',
      'https://www.techreviewer.co/directory',
      'https://www.topdigital.agency/directory',
      'https://www.businessofapps.com/agency-directory/',
      'https://www.digital.com/directory/',
      'https://www.themanifest.com/agencies',
      'https://www.agencyspotter.com/agencies',
      'https://www.upcity.com/agencies',
      'https://www.topseos.com/directory',
      'https://www.marketingagencyhub.com/',
      'https://www.goodfirms.co/seo-companies',
      'https://www.appsrhino.com/directory',
      'https://www.designrush.com/agency/top-web-development',
      'https://www.techreviewer.co/top-software-development-companies',
      'https://www.itfirms.co/top-web-development-companies',
      'https://www.agencyspotter.com/',
      'https://www.clutch.co/web-developers',
      'https://www.inc.com/',
      'https://www.forbes.com/',
      'https://www.crunchbase.com/',
      'https://www.techradar.com/news/software-companies',
      'https://www.topdevelopers.co/',
      'https://www.99firms.com/',
      'https://www.sortlist.com/',
      'https://www.businessofapps.com/',
      'https://www.digital.com/',
      'https://www.themanifest.com/',
      'https://www.upcity.com/',
      'https://www.marketingagencyhub.com/',
      'https://www.appfutura.com/',
      'https://www.expertmarket.co.uk/',
      'https://www.appsrhino.com/',
      'https://www.techreviewer.co/',
      'https://www.itfirms.co/',
      'https://www.goodfirms.co/directory/web-development',
      'https://www.clutch.co/directory/web-developers',
      'https://www.topdigital.agency/directory/web-development',
      'https://www.designrush.com/agency/web-development',
      'https://www.agencyspotter.com/agencies/web-development',
      'https://www.sortlist.com/agencies/web-development',
      'https://www.upcity.com/agencies/web-development',
      'https://www.themanifest.com/web-development',
      'https://www.inc.com/top-companies',
    ],
  };

  return (
    <html lang="en">
      <body className={`${urbanist.variable} antialiased`}>
        <Loader />
        {children}
      </body>
    </html>
  );
}
